[package]
name = "fm_benchmark"
version = "0.1.0"
authors = ["Skrytt"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sample = "0.10"

[lib]
name = "fm_benchmark"
path = "src/lib.rs"
crate-type = ["rlib"]
