---
version: 2.1
jobs:
    jack-build:
        docker:
            - image: circleci/rust:latest
        working_directory: ~/baselisk-rs
        steps:
            - checkout
            - run:
                  name: Version information
                  command: |
                      rustc --version
                      cargo --version
                      rustup --version
            - run:
                  name: Install dependencies (APT)
                  command: |
                      sudo apt-get update
                      sudo apt-get install -y libjack-dev
            - run:
                  name: Check JACK client crate builds
                  command: cargo build --manifest-path jack/Cargo.toml
            - run:
                  name: Check VST client crate builds
                  command: cargo build --manifest-path vst/Cargo.toml
            - run:
                  name: Run core crate tests
                  command: RUST_BACKTRACE=1 cargo test --manifest-path core/Cargo.toml

workflows:
    version: 2.1
    build:
        jobs:
            - jack-build
